steps:
  - name: codespell
    when:
      - event: [manual, pull_request]
      - event: [push, tag]
        branch: [master, releases/*]
    image: alpine:edge
    commands:
      - apk add openssl
      - apk add python3
      - apk add py3-pip
      - python3 -m venv codespell-venv
      - source codespell-venv/bin/activate
      - pip install codespell
      - codespell README.md CHANGELOG.md *.c *.h doc/*.scd

  - name: subprojects
    when:
      - event: [manual, pull_request]
      - event: [push, tag]
        branch: [master, releases/*]
    image: alpine:edge
    commands:
      - apk add git
      - mkdir -p subprojects && cd subprojects
      - git clone https://codeberg.org/dnkl/tllist.git
      - git clone https://codeberg.org/dnkl/fcft.git
      - cd ..

  - name: x64
    when:
      - event: [manual, pull_request]
      - event: [push, tag]
        branch: [master, releases/*]
    depends_on: [subprojects]
    image: alpine:edge
    commands:
      - apk update
      - apk add musl-dev linux-headers meson ninja gcc clang scdoc
      - apk add libxkbcommon-dev cairo-dev yaml-dev librsvg-dev
      - apk add wayland-dev wayland-protocols wlroots-dev
      - apk add git

      # Debug (default: cairo, nanosvg(bundled), libpng)
      - mkdir -p bld/debug-x64
      - meson setup --buildtype=debug . bld/debug-x64
      - ninja -C bld/debug-x64 -k0
      - bld/debug-x64/fuzzel --version

      # Release (gcc)
      - mkdir -p bld/release-x64
      - meson setup --buildtype=release . bld/release-x64
      - ninja -C bld/release-x64 -k0
      - bld/release-x64/fuzzel --version

      # Release (clang)
      - mkdir -p bld/release-x64-clang
      - CC=clang meson setup --buildtype=release . bld/release-x64-clang
      - ninja -C bld/release-x64-clang -k0
      - bld/release-x64-clang/fuzzel --version

      # Debug (no cairo, no icons)
      - mkdir -p bld/no-cairo-no-icons
      - meson setup --buildtype=debug -Denable-cairo=disabled -Dpng-backend=none -Dsvg-backend=none . bld/no-cairo-no-icons
      - ninja -C bld/no-cairo-no-icons -k0
      - bld/no-cairo-no-icons/fuzzel --version

  - name: x86
    when:
      - event: [manual, pull_request]
      - event: [push, tag]
        branch: [master, releases/*]
    depends_on: [subprojects]
    image: i386/alpine:edge
    commands:
      - apk update
      - apk add musl-dev linux-headers meson ninja gcc clang scdoc
      - apk add libxkbcommon-dev cairo-dev yaml-dev librsvg-dev
      - apk add wayland-dev wayland-protocols wlroots-dev
      - apk add git

      # Debug (default: cairo, nanosvg(bundled), libpng)
      - mkdir -p bld/debug-x86
      - meson setup --buildtype=debug . bld/debug-x86
      - ninja -C bld/debug-x86 -k0
      - bld/debug-x86/fuzzel --version

      # Release (gcc)
      - mkdir -p bld/release-x86
      - meson setup --buildtype=release . bld/release-x86
      - ninja -C bld/release-x86 -k0
      - bld/release-x86/fuzzel --version

      # Release (clang)
      - mkdir -p bld/release-x86-clang
      - CC=clang meson setup --buildtype=release . bld/release-x86-clang
      - ninja -C bld/release-x86-clang -k0
      - bld/release-x86-clang/fuzzel --version

      # Debug (cairo, librsvg, no png)
      - mkdir -p bld/cairo-librsvg-no-png
      - meson setup --buildtype=debug -Denable-cairo=enabled -Dpng-backend=none -Dsvg-backend=librsvg . bld/cairo-librsvg-no-png
      - ninja -C bld/cairo-librsvg-no-png -k0
      - bld/cairo-librsvg-no-png/fuzzel --version
